### ISSUE TITLE
Engineering Documentation...

### ISSUE THREAD

**Issue by hchasey** [desiringgod/guides#40]
Coming out of [our Thur, Aug 3, 2017 meeting](https://trello.com/c/JAlUh2pU/48-engineering-documentation), there's a concern about engineering documentation....

@shanebo – can you articulate the concern and/or main question here.

cc @pjmelling @joeosburn-desiringgod @scottcorgan

**Comment by shanebo** [comment]
@hchasey sure.

My premise is basically this: as the team grows in both number, timezones, remote/on-site, areas of focus, schedules, etc., communication has more opportunities for failure. So, when various team members aren't present or miss a drive-by engineering comment/update in slack, they need to know where to go for the latest documentation on a given thing when they hit a snag. Granted, documentation won't always be perfect or up to date, but it's better to have 95% accurate documentation with a disclaimer then none at all.

Solution ideas:

1. Decide as a team where documentation should live (Dropbox Paper, related github repo, etc.?)
2. Go through existing documentation, update it as needed, and move if applicable in light of point 1.
3. Ongoing, whoever wants to notify the team of a change in tech, approach, execution, first they're responsible to update documentation, and when the team is notified they link up to the documentation. If certain people never see the notification they'll know where to look for docs on a given project.
4. Maybe we have a central doc in Dropbox Paper that outlines this workflow and links up to all documentation from a macro standpoint.

**Comment by benhutton** [comment]
@shanebo can you give some examples of things from the recent past that would get included in the documentation?

**Comment by shanebo** [comment]
@benhutton sure. Off the cuff examples:

- Moving from `rails s` to `bin/server`
- Installation of yarn
- Frontend patterns with webpack's client directory. That is, where do we put assets now? Do we still use things like the `image_tag`helper to set paths to images, or do we statically set absolute paths or relative paths, etc.

**Comment by benhutton** [comment]
@shanebo gotcha. I see the value in having good docs on that stuff. At the same time, I'm not sure I see how they would tactically fit into solving the problems of people who hadn't gotten the message when it was first promulgated. 

It seems like there's often a weird error that someone needs help with. Are we going to create a database of weird errors and the steps to fix them? Or should that error cause them to go look in the docs? How would they find what they need?

I feel like the current practice of just asking for help in slack seems to be the most efficient thing we're going to come up with, don't you?

**Comment by shanebo** [comment]
@benhutton basically I'd imagine something like:

1. Someone hits a snag
2. Based on some logical principle we'd establish in point 1 of my solution ideas, they'd go look for a solution where the docs should be
3. If there are related docs they try them
4. If the docs don't resolve things they ask for help
5. After resolution they update the docs

**Comment by hchasey** [comment]
Thanks @shanebo – the description and these examples are helpful! This sparks some questions I've been kicking around a bit, and thus, might break out this issue into a few more distinct questions....
