### ISSUE TITLE
Where Should Engineering Documentation Go?

### ISSUE THREAD

**Issue by hchasey** [desiringgod/guides#41]
Branching off of issue #40, a question embedded in that thread is: where is the canonical location for engineering documentation? 

I'll respond here with some options that you 👍 or 👎 and @desiringgod/engineers you can propose other ideas.

**Comment by hchasey** [comment]
Dropbox Paper

**Comment by hchasey** [comment]
Google Drive / Docs / Sheets / Slides

**Comment by hchasey** [comment]
GitHub – everything in https://github.com/desiringgod/guides/

**Comment by hchasey** [comment]
GitHub – everything in whatever repo the docs are related to

**Comment by hchasey** [comment]
GitHub – mix of https://github.com/desiringgod/guides/ and repo-specific docs

**Comment by hchasey** [comment]
slack

**Comment by hchasey** [comment]
Assigning to the engineer who have not voted. Once you vote, remove yourself, and if you're last, assign this back to me 👍

**Comment by pjmelling** [comment]
@joeosburn-desiringgod I think this one's in your court, then pass it back to Ross.
