### ISSUE TITLE
Front End File Naming Convention

### ISSUE THREAD

**Issue by scottcorgan** [desiringgod/guides#44]
Ref the question in Slack https://desiringgod.slack.com/archives/C4J34L091/p1503314552000011

---

What is our file naming scheme for client-side files. It seems to use both `kebab-case` and `snake_case`.

I want to recommend we choose one for all files, probably `snake_case`, since that's the Ruby convention.

Thoughts?

**Comment by hchasey** [comment]
`kebab-case`

**Comment by hchasey** [comment]
`snake_case`

**Comment by hchasey** [comment]
Other – Please comment....

**Comment by hchasey** [comment]
@desiringgod/engineers – please vote and then un-assign yourself. Whoever is last can reassign to @scottcorgan to document :)

**Comment by scottcorgan** [comment]
@hchasey thanks for making the vote. That's a good idea!

**Comment by hchasey** [comment]
@scottcorgan – I don't think that `snake_case` can be overruled by the remaining voters, so I'd say feel free to document this to close out this issue. Then, we can make the changes in the code.
