### ISSUE TITLE
Hound?

### ISSUE THREAD

**Issue by ryanjames** [desiringgod/guides#56]
I saw a reference to Hound in the [style](https://github.com/desiringgod/guides/tree/master/style) section and the idea of checking our styling with it sounds cool, but it appears only a repo's admin can add/activate it once I linked my Github account to the tool. Are we going to start using it?

**Comment by benhutton** [comment]
I'd rather use their underlying linters in CI. That's how we already are doing it for rubocop and eslint.

**Comment by ryanjames** [comment]
@benhutton Yeah, Peter mentioned that the initial doc was Thoughtbot's template so none of us had suggested Hound. Closing.
